sudo: required

language: java

services:
  - docker

jdk:
  - oraclejdk8

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - bash <(curl -s https://codecov.io/bash)

  - export REPO=mwvdev/berightthere
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - export JAR_FILE=$(ls ./build/libs/berightthere-*.jar)

  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

  - docker build --build-arg JAR_FILE=$JAR_FILE -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG

  - docker push $REPO

notifications:
  slack:
    secure: q/GLAIsr6YBMtIzrLX9gfq2JQcgdDU+CW9R38qP0phZp2g680XRvdMEbH5kEeSAvZmcqb7omJuv6IIxCJl/ny8woeVBZn2RH7qxNb180vkIDmET4cE0eq7PWqf0dufe9Sz+a1/+Qvyi4lAdUCWdhywijzZ5Uhh6cz/j1vyahWvSLxJZfbh1/ne6LcsbHMiET5WpaV2UZ/1sa/LZ48clbX4rHujpnuz0bblCD6ZAxfbBL1SAaYzPDASlDy536/dDK62cG6P/tfSr3NOxdos7s3H48kchkOiP+efIcSlmZ9LT5bMVfJzo6Zm+aeVHEt+B+CpQU3hBDog721Cc6PvuP3FDs+01x514HD3kcKbQd4yraqw/138RP5KIJS7eSlks4uxQdhQ4HEhzjuFdb8fFuuBumwK75hd+zG45NrYlVnjpwLXW9/kV97T9aXsYsAbmCeIVfQZ1UhAcQ/ri2OAkHVLZcrfGgdzoVLBQcQOtNFP29BA1wLnmtFAQuUFptqMyNTy9XuMBGADryxUCfNYDBgRA+Lzd/rpsDBVTWj0UA+AhwOCuXMK+D9PlHmOXO0ojtPycDjrl0EBb4Azb7ypBjuzxDJYbpJgxQP74i01j/6+4pNMWRuwON4aPDSXiRAa6//V2eGlreJCFmTp3+0F5bqzKgwNnSEciPD63iXkvp008=
